# Generated by Django 4.0.6 on 2022-07-05 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capital', models.CharField(max_length=100)),
                ('img_country', models.ImageField(blank=True, null=True, upload_to='country_image', verbose_name='Изображение страны')),
                ('img_capital', models.ImageField(blank=True, null=True, upload_to='capital_image', verbose_name='Изображение столицы')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
    ]
