# Generated by Django 3.2.9 on 2022-07-07 09:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_country_capital_alter_country_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Continent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('img', models.ImageField(blank=True, null=True, upload_to='сontinent_image', verbose_name='Изображение континента')),
            ],
            options={
                'verbose_name': 'Континент',
                'verbose_name_plural': 'Континенты',
            },
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Группа стран',
                'verbose_name_plural': 'Группы стран',
            },
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
        migrations.AddField(
            model_name='country',
            name='info',
            field=models.TextField(blank=True, max_length=10000, null=True),
        ),
        migrations.AddField(
            model_name='country',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='main.group'),
        ),
        migrations.AddField(
            model_name='country',
            name='сontinent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='countries', to='main.continent'),
        ),
    ]
