# Generated by Django 3.2.9 on 2022-07-08 11:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_country_сontinent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.group', verbose_name='Группа стран'),
        ),
        migrations.AlterField(
            model_name='country',
            name='сontinent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.continent', verbose_name='Континент'),
        ),
    ]
